# Generated by Django 2.2.2 on 2020-03-03 17:08

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='avatars', verbose_name='Player profile image'),
        ),
    ]
