# Generated by Django 2.2.2 on 2020-03-03 01:19

from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200302_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certifications',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Assistent Ref'), ('S', 'Snitch Ref'), ('H', 'Head Ref')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='positions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'Chaser'), ('K', 'Keeper'), ('B', 'Beater'), ('S', 'Seeker')], max_length=7, null=True),
        ),
    ]
