# Generated by Django 2.2.2 on 2020-03-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ngb', models.CharField(choices=[('AQArg', 'Argentina'), ('QA', 'Australia'), ('QAT', 'Austria'), ('BQF', 'Belgium'), ('ABRQ', 'Brasil'), ('QC', 'Canada'), ('AQC', 'Catalonia'), ('ACQ', 'Chile'), ('CAF', 'Czech Republic'), ('DQF', 'Denmark'), ('QF', 'Finland'), ('FQF', 'France'), ('DQB', 'Germany'), ('HKQA', 'Hong Kong'), ('QSÍ', 'Iceland'), ('QI', 'India'), ('QIRE', 'Ireland'), ('AIQ', 'Italy'), ('JQA', 'Japan'), ('QM', 'Malaysia'), ('QMX', 'México'), ('QNL', 'Netherlands'), ('QNZ', 'New Zealand'), ('NRF', 'Norway'), ('FDPQ', 'Peru'), ('PLQ', 'Poland'), ('QPt', 'Portugal'), ('QK', 'Korea'), ('QS', 'Serbia'), ('SQA', 'Slovakia'), ('QSVN', 'Slovenia'), ('AQE', 'Spain'), ('SvQF', 'Sweden'), ('SQV', 'Switzerland'), ('QD', 'Turkey'), ('QU', 'Uganda'), ('QUK', 'UK'), ('VQA', 'Vietnam'), ('Other', 'Not listed')], max_length=5)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='team_logos', verbose_name='Team Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('r', 'Requested'), ('p', 'Pending Approval'), ('a', 'Approved')], max_length=1)),
                ('approval', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('r', 'Requested'), ('p', 'Pending Approval'), ('a', 'Approved')], max_length=5, null=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_team', to='teams.Team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_team', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
