# Generated by Django 2.2.2 on 2020-03-03 22:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='from_ngb',
            field=models.CharField(blank=True, choices=[('AQArg', 'Argentina'), ('QA', 'Australia'), ('QAT', 'Austria'), ('BQF', 'Belgium'), ('ABRQ', 'Brasil'), ('QC', 'Canada'), ('AQC', 'Catalonia'), ('ACQ', 'Chile'), ('CAF', 'Czech Republic'), ('DQF', 'Denmark'), ('QF', 'Finland'), ('FQF', 'France'), ('DQB', 'Germany'), ('HKQA', 'Hong Kong'), ('QSÍ', 'Iceland'), ('QI', 'India'), ('QIRE', 'Ireland'), ('AIQ', 'Italy'), ('JQA', 'Japan'), ('QM', 'Malaysia'), ('QMX', 'México'), ('QNL', 'Netherlands'), ('QNZ', 'New Zealand'), ('NRF', 'Norway'), ('FDPQ', 'Peru'), ('PLQ', 'Poland'), ('QPt', 'Portugal'), ('QK', 'Korea'), ('QS', 'Serbia'), ('SQA', 'Slovakia'), ('QSVN', 'Slovenia'), ('AQE', 'Spain'), ('SvQF', 'Sweden'), ('SQV', 'Switzerland'), ('QD', 'Turkey'), ('QU', 'Uganda'), ('QUK', 'UK'), ('VQA', 'Vietnam'), ('Other', 'Not listed')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='reason',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='approval',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('f', 'FROM APPROVED'), ('t', 'TO APPROVED'), ('l', 'LEAGUE APPROVED'), ('n', 'NGB APPROVED')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_team', to='teams.Team'),
        ),
    ]
