# Generated by Django 2.2.2 on 2020-03-03 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200303_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='state',
            field=models.CharField(choices=[('r', 'Requested'), ('p', 'Pending Approval'), ('a', 'Approved')], default='r', max_length=1),
        ),
    ]
