# Generated by Django 2.2.2 on 2020-03-04 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200303_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='from_team',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='teams.Team'),
        ),
    ]
