# Generated by Django 2.2.2 on 2020-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200304_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='state',
            field=models.CharField(choices=[('r', 'Requested'), ('p', 'Pending Approval'), ('a', 'Approved'), ('o', 'Old')], default='r', max_length=1),
        ),
    ]
