# Generated by Django 2.2.2 on 2020-03-04 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0006_auto_20200304_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='teams.Transfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
