# Generated by Django 2.2.2 on 2020-03-04 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='memberships', through='teams.Transfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
