# Generated by Django 2.2.2 on 2020-03-04 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0008_auto_20200304_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Role',
        ),
    ]
