# Generated by Django 2.2.2 on 2020-03-04 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0009_auto_20200304_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='staff',
            field=models.ManyToManyField(related_name='roles', through='teams.Role', to=settings.AUTH_USER_MODEL),
        ),
    ]
